### ISSUE TITLE
key_sequence() method doesn't take line return into account.

### ISSUE THREAD

**Issue by thomaslc66** [enigo-rs/enigo#175]
**Describe the bug**
I my text is like that:
Q: What did the fish say when it hit the wall?
A: Dam!

Enigo keyboard will print it like that: Q: What did the fish say when it hit the wall?A: Dam!

**To Reproduce**
Pass the text formated to a key_sequence()

**Expected behavior**
key_sequence() method should print the text formated.

**Comment by pentamassiv** [comment]
I can't reproduce this. Which version of `enigo` are you using and on which OS?
Please try to reproduce the issue by cloning the repo and then changing the `keyboard` example to enter your text. Then run `cargo run --example keyboard` to check if the bug is related to your code or `enigo` itself.

I also noticed that you are using Tauri in your project. We have had a few reports of issues with Tauri+enigo (https://github.com/enigo-rs/enigo/issues/174, https://github.com/enigo-rs/enigo/issues/153, https://github.com/tauri-apps/tauri/issues/6421).

**Comment by pentamassiv** [comment]
Did you test it?

**Comment by pentamassiv** [comment]
Fixed
