### ISSUE TITLE
Media keys Windows only?

### ISSUE THREAD

**Issue by ShayBox** [enigo-rs/enigo#179]
Why are the Media keys Windows only? they work cross-platform on Windows, macOS, and Linux

https://github.com/enigo-rs/enigo/blob/c53be78a4cdbd2d19ccda59f990050d8591bb969/src/keycodes.rs#L356-L363

EDIT: A lot of these keys work cross-platform, why are so many of them made Windows only?
EDIT2: The library is definitely not cross-platform if most of the keys are compilation-locked Windows only and require sending the same raw key to work cross-platform...

**Comment by pentamassiv** [comment]
The reason why some keys are Windows, macOS or Linux only is because I am unaware of a complete list describing which keys are equivalent on which platform. There are hundreds of keys and they often have different names. This is a volunteer project and there are other more important issues to fix. I gave my best to find keys that are equivalent but I am not going to spend hours on it. If I missed something, a user of the library can quickly open an issue and we can fix it and publish a new version. Usually I react within a week and can publish a new version. I was more busy than usual so it took a longer time for me to react this time.

**Comment by pentamassiv** [comment]
We have an issue to remind us to improve on the equivalence between the keys https://github.com/enigo-rs/enigo/issues/164
