### ISSUE TITLE
Mouse does not move on macOS unless `mouse_location` is called after moving the mouse

### ISSUE THREAD

**Issue by pokir** [enigo-rs/enigo#182]
**Describe the bug**
The code below doesn't move the mouse on macOS unless a specific combination of function calls is used (see **Additional context** below).

**To Reproduce**
```rs
use enigo::{Enigo, MouseControllable};

fn main() {
    let mut enigo = Enigo::new();
    enigo.mouse_move_to(0, 0);
}
```

**Expected behavior**
Mouse moves to (0, 0).

**Environment (please complete the following information):**

- OS: macOS 12.6
- Rust: rustc 1.70.0 (90c541806 2023-05-31)
- Library Version: enigo 0.1.2

**Additional context**
I used this to circumvent the bug:

```rs
fn prevent_bug_that_causes_mouse_not_to_move(enigo: &mut Enigo) {
    let (x, y) = enigo.mouse_location();

    // move the mouse anywhere first (the mouse needs to move once before calling mouse_location)
    // so it is moved to where it already is
    enigo.mouse_move_to(x, y);

    // this mouse_location call makes the mouse able to move now
    let _ = enigo.mouse_location();
}
```

Any `mouse_move_to` calls work as expected after calling this function.

**Comment by pentamassiv** [comment]
Thank you for the report, I haven't noticed that on the mac I tested it with. I have to look into it

**Comment by pentamassiv** [comment]
I believe this is a timing issue again. For some reason it is more likely to happen if you move the mouse to (0,0). Maybe that is the reason why it seemed like the following mouse moves will work. When I replaced the `mouse_loc()` with a sleep, it worked reliably as well.

Interestingly I was also able to replace the sleeps in the other parts of the code on macOS with `mouse_loc()`. I need to find out if that is because it takes some time or if it somehow fixes the queuing issues and a sleep becomes unnecessary. It would be super helpful if that were the case
