### ISSUE TITLE
[Performance Issue] Enigo blocks other inputs while clicking

### ISSUE THREAD

**Issue by HyperCodec** [enigo-rs/enigo#186]
I currently have a program that runs `enigo.mouse_click(MouseButton::Left)` (where `enigo` is a variable of `Enigo::new()`) many times in a short period, but it lags all other inputs behind when it does so. It appears to be an issue with Enigo, as the exact same code ported to Python, using `pyautogui` instead of `Enigo`, doesn't do this.

Does anyone know of a more optimized framework that can run mouse clicks and/or key presses for Rust? Is there a more optimized Enigo function? I'm currently running on Windows 10 for this project if that helps at all.

Edit: no one replied so I hope this will bump it and someone comes across it that knows a solution.

This issue is a copy of my [StackOverflow question](https://stackoverflow.com/questions/75272639/rust-enigo-crate-blocking-other-inputs-when-clicking), from which I was directed to create an issue

**Comment by HyperCodec** [comment]
you can ignore the second paragraph, I'm probably going to have to just wait until this is better optimized or something

**Comment by pentamassiv** [comment]
Thank you for your report. If you experience any problems with `enigo` or have other questions, opening issues in this repo is the right place to ask. I don't monitor stackexchange for questions related to enigo.

Regarding your question: Yes, unfortunately this is a known problem. Windows seems to need a delay between the keydown and the keyup event. We have an intentional delay in the code (e.g. [here](https://github.com/enigo-rs/enigo/blob/c53be78a4cdbd2d19ccda59f990050d8591bb969/src/win/win_impl.rs#L232)). If you call it many times in a loop, everything afterwards is delayed because we don't enter it in parallel.

A workaround that might work for you could be to call
```
enigo.mouse_down(MouseButton::Left)
enigo.mouse_up(MouseButton::Left)
```
in the loop. Those functions intentionally don't have a delay. You probably have to sleep for a couple of milliseconds in between. Otherwise it might not click the expected number of times.

If you want to enter text, it is better to use the `key_sequence` function. It also has a delay, but it can enter multiple characters at once.

I had a brief look at the code of the python library you mentioned and I can't see a delay there. I have to look more into it to understand how they can avoid it. It would be very welcome if we could get rid of it.

I am closing this for now. We have an issue regarding the delay already: https://github.com/enigo-rs/enigo/issues/45

Feel free to reopen the issue, if you have more questions :-)
