### ISSUE TITLE
character sequence manual delay

### ISSUE THREAD

**Issue by sloganking** [enigo-rs/enigo#238]
**Is your feature request related to a problem? Please describe.**
Typing is still slower than desired for me. Which was outlined in #38. 

**Describe the solution you'd like**
It works on my machine if I replace the sleep statement with a very low value. Can we allow users to pass a duration to the function to specify the sleep time between key presses manually?

**Comment by pentamassiv** [comment]
This is already done. If you use the master branch, you can try it out. Have a look at the changelog. It allows you to specify the delay on the platform via the `EnigoSettings` struct. You can also change it during the runtime. On Windows, there no longer are any delays needed. There were a number of breaking changes so you will need to slightly change your code to work with the master branch though. There are two new traits. If you use them directly, the functions will return errors instead of panicking. Please pin your enigo version to a commit if you try it out, because I am actively working on it and am breaking stuff on a daily basis. Add this to your Cargo.toml for example:
```
enigo = { git = "https://github.com/enigo-rs/enigo.git", rev = "96d5fd2b461fbe61e44473437356b2e2905dbc50" }
```
Hopefully I will be able to publish a new version soon. Then you can switch back to the crates.io version. Let me know what you think of the changes. If you don't like anything, maybe I can change it before publishing a new version.

**Comment by sloganking** [comment]
Awesome! I'll update my local installation for now and update the crate on `crates.io` when a new `enigo` version comes out. Thanks for the speedy and helpful reply!
