### ISSUE TITLE
Hi, there. Is there any way to click on a specified relative coordinate of a window that is in the background but not minimized, without bringing it to the foreground, and without affecting the mouse operations in the foreground window?

### ISSUE THREAD

**Issue by qzd1989** [enigo-rs/enigo#317]
**Describe your Goal**
I want to open a window in the background, then click somewhere of it, and still keep it in the background, without interrupting my mouse operations of foreground window.

**Environment (please complete the following information):**

- OS: Windows, macOS
- Rust rustc 1.82.0-nightly (13a52890d 2024-08-14)
- Library Version v0.2.1

**Comment by qzd1989** [comment]
oh my god... I encounterd this problem   https://github.com/enigo-rs/enigo/issues/153

**Comment by pentamassiv** [comment]
Hi, 
right now this it's not implemented because it is only possible on Windows and Linux X11. Since this library tries to work on all platforms, platform specific features are not a priority. I first want to fix the issues that currently exist.

Sorry about the Tauri issue. It's pinned in the issue tab so that it's more obvious, but most people probably only look at that once they encountered the problem.

Have you enabled all required permissions for your application? I thought the crash was due to the lack of permissions

**Comment by qzd1989** [comment]
Thank you, sir, I'm very appreciate your answer.
This important message about 'it being only possible on Windows and Linux X11' is very helpful to me.
thank you again.
