### ISSUE TITLE
Inconsistent pixel units

### ISSUE THREAD

**Issue by ArturKovacs** [enigo-rs/enigo#91]
Hello! From windows 10 the parameters of `mouse_move_to` seem to be physical-pixel-units but the parameters of `mouse_move_relative` seem to be logical-pixel-units. The two functions should preferably operate on the same units and the kind of units should be stated in the documentation.

Minimal code example:
```rust
let mut enigo = Enigo::new();
enigo.mouse_move_to(100, 100);
// Comment out the following function call and un-comment the line after
// and the cursor will end up at a different location if the display scaling is not a 100%
enigo.mouse_move_to(150, 150);
//enigo.mouse_move_relative(50, 50);
```

 - OS: Windows 10
 - Rust: `rustc 1.41.1 (f3e1a954d 2020-02-24)`
 - Library Version: enigo 0.0.14

**Comment by FlareFlo** [comment]
I stumbled on the same problem and found it was related to the windows mouse speed setting

**Comment by pentamassiv** [comment]
I looked at the [documentation](https://learn.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-mouseinput#members) and our code and the reason why there is a difference between `mouse_move_to` and `mouse_move_relative` is because of the flag `MOUSEEVENTF_VIRTUALDESK`. The docs say:
> Maps coordinates to the entire desktop. Must be used with MOUSEEVENTF_ABSOLUTE.


So I seems to be impossible to be used in `mouse_move_relative`. In order to get a consistent behavior between both functions, I believe we have to call `mouse_location` and then calculate the new coordinates.

**Comment by FlareFlo** [comment]
maybe make a wrapper function that does exactly that? the regular `relative_move `function seems pretty useless if it has such issue

**Comment by FlareFlo** [comment]
awesome!

**Comment by soni801** [comment]
This bug seems to have been reintroduced at some point, likely while refactoring the mouse movement code(?)

I've confirmed that the issue is apparent with enigo 0.2.1 on Windows 11 (23H2), using `cargo run` with cargo version `cargo 1.80.1 (376290515 2024-07-16)`

Reproducible code:
```rust
use std::process;
use enigo::{Coordinate, Enigo, Mouse, Settings};

fn main() {
    let mut enigo = Enigo::new(&Settings::default()).unwrap_or_else(|error| {
        println!("Failed to initialize Enigo: {error}");
        process::exit(1);
    });

    // Move to 0, 0 (this works)
    let _ = enigo.move_mouse(0, 0, Coordinate::Abs);

    // Log current position for sanity
    let pos = enigo.location().unwrap();
    println!("Current pos: {}, {}", pos.0, pos.1);

    // Move to 200, 200 using absolute movement (this works)
    let _ = enigo.move_mouse(200, 200, Coordinate::Abs);

    // Log current position for sanity
    let pos = enigo.location().unwrap();
    println!("Current pos: {}, {}", pos.0, pos.1);

    // Now, let's look at relative movement!
    // First, let's reset the mouse to 0, 0 again using absolute movement one last time (this works)
    let _ = enigo.move_mouse(0, 0, Coordinate::Abs);
    let pos = enigo.location().unwrap();
    println!("Current pos: {}, {}", pos.0, pos.1);

    // Now, look at what happens when I try to move the mouse to 200, 200 using relative movement (doesn't work!)
    let _ = enigo.move_mouse(200, 200, Coordinate::Rel);

    // Log current position - it's wrong!
    let pos = enigo.location().unwrap();
    println!("Current pos: {}, {}", pos.0, pos.1);
}
```

When ran, this outputs the following:
```
Current pos: 0, 0
Current pos: 200, 200
Current pos: 0, 0
Current pos: 100, 100
```

**Comment by pentamassiv** [comment]
On main the behavior was correct, but not consistent with the other platforms. The mouse speed and acceleration levels changed the coordinate that the mouse move resulted in. I created https://github.com/enigo-rs/enigo/pull/358 to address this.
