### ISSUE TITLE
Pressing "Pagedown" outputs "3" without scrolling down (Windows 10)

### ISSUE THREAD

**Issue by lowleveldata** [enigo-rs/enigo#99]
Video:
![output](https://user-images.githubusercontent.com/25565894/99135043-d0b3e380-2663-11eb-9e7c-a66b5127716a.gif)

**To Reproduce**
```rust
use enigo::{Enigo, Key, KeyboardControllable};
use std::thread;
use std::time::Duration;

fn main() {    
    let mut enigo = Enigo::new();
    
    loop {
        thread::sleep(Duration::from_secs(2));
        println!("Pressing pagedown");
        enigo.key_click(Key::PageDown);        
    }      
}
```

**Environment (please complete the following information):**
 - OS: Windows 10
 - rustc 1.47.0 (18bf6b4f0 2020-10-07)
 - enigo = "0.0.14"

**Additional context**
Have not tested on other OS so not sure if it is a windows only issue. I also find that `mouse_scroll_y` scrolls up when given a positive number which should be the opposite according to the document. Windows 10 doing weird things?

**Comment by mefechoel** [comment]
I had a similar problem, when I tried to simulate a `LeftArrow` keyclick, a `4` was typed. It turned out, that thats what the left arrow on the numpad maps to. When I turned off the numpad it worked as expected. This also explains why in your case a 3 was pressed. `PageDown` maps to `3` on the numpad.

I've had a quick look through the code and could identify where the issue arises:
When `key_click` is called it first converts the key (`Key::PageDown` for example) to a virtual keycode in `key_to_scancode`. It the converts the virtual keycode to a scancode using winapi's `MapVirtualKeyW` function. I think this is the point where windows checks the virtual key against whatever mode your keyboard is in and in our case detects that the numpad is active. It translate the key to the appropriate numbers scan code which it returns to `key_click`. `key_click` then calls `keybd_event` with the incorrect scan code, rather than with a virtual keycode and it issues the keypress using winapi's `SendInput` function.

I was just using the function for a really simple use case, so I replaced the `key_click` function when running windows with this:

```rs
pub fn key_click(key: WinKey) {
	// Don't convert the key to a scan code.
	// Just use the virtual keycode.
	let keycode = get_key_code(key);
	use std::{thread, time};
	// We want to use the virtual keycode instead of a scancode,
	// so we don't set the `KEYEVENTF_SCANCODE` flag.
	// A regular keypress without any options will be issued.
	keybd_event(0, keycode);
	thread::sleep(time::Duration::from_millis(20));
	keybd_event(KEYEVENTF_KEYUP, keycode);
}
```

with the `get_key_code` function looking something like this:

```rs
pub enum WinKey {
	PageUp,
	PageDown,
	/* ... */
}

fn get_key_code(key: WinKey) -> u16 {
	let key_code = match key {
		WinKey::PageUp => VK_PRIOR, // 0x21
		WinKey::PageDown => VK_NEXT, // 0x22
		/* ... */
	};
	key_code as u16
}
```

and the modidied `keybd_event` like this:

```rs
fn keybd_event(flags: u32, vk: u16) {
	let mut input = INPUT {
		type_: INPUT_KEYBOARD,
		u: unsafe {
			transmute_copy(&KEYBDINPUT {
				wVk: vk,
				// We're just using vitual keycodes,
				// so we're setting the scancode to 0
				wScan: 0,
				dwFlags: flags,
				time: 0,
				dwExtraInfo: 0,
			})
		},
	};
	unsafe { SendInput(1, &mut input as LPINPUT, size_of::<INPUT>() as c_int) };
}
```

I'm not too familiar with enigo's code base, so I'm not sure why everything is converted to a scancode in the first place. I'm sure it's there for a reason and it would probably break something if it would just always use virtual keycodes... But maybe this helps a little in fixing the issue.

**Comment by mefechoel** [comment]
I created pr (#100) to help with the issue. I hope it'll help you as a basis to fix this.

**Comment by pythoneer** [comment]
Thanks for your investigation @mefechoel and your PR. I need to dig through this myself because – as you mentioned – there needs to be a reason for that behavior in the first place but i don't know it right now from memory.

**Comment by pentamassiv** [comment]
It has been a while since this issue was opened. Did a reason come up, why we cannot use virtual keycodes? If not, should we change the behavior?

**Comment by pentamassiv** [comment]
The issue was fixed
